/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const __wbg_remoteconn_free: (a: number, b: number) => void;
export const connect: (a: number, b: number, c: any, d: any) => any;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const remoteconn_close: (a: number) => void;
export const remoteconn_fetchAsset: (a: number, b: number, c: number) => any;
export const remoteconn_send: (a: number, b: number, c: number) => void;
export const start: () => void;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke___js_sys_b950eefca4bec31a___Function_fn_wasm_bindgen_417b166963dc747___JsValue_____wasm_bindgen_417b166963dc747___sys__Undefined___js_sys_b950eefca4bec31a___Function_fn_wasm_bindgen_417b166963dc747___JsValue_____wasm_bindgen_417b166963dc747___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke___wasm_bindgen_417b166963dc747___JsValue__core_ed718c3d60ebd546___result__Result_____wasm_bindgen_417b166963dc747___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke___wasm_bindgen_417b166963dc747___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke___web_sys_da64c89f2b14f18f___features__gen_CloseEvent__CloseEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke___web_sys_da64c89f2b14f18f___features__gen_MessageEvent__MessageEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke_______true__2_: (a: number, b: number) => void;
export const wasm_bindgen_417b166963dc747___convert__closures_____invoke_______true__3_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
